### ISSUE TITLE
Rotated coordinates are not shown correctly with plot="poly"

### ISSUE THREAD

**Issue by Chilipp** [psyplot/psy-maps#28]
#### Code Sample, a copy-pastable example if possible

take [psy-views rotated-pole-test.nc file](https://github.com/psyplot/psy-view/blob/master/tests/rotated-pole-test.nc) for instance, and plot it via

```python
psy.plot.mapplot("rotated-pole-test.nc", plot="poly", name="t2m")
```
#### Problem description
The grid cell boundaries are not transformed correctly, what you get is

![image](https://user-images.githubusercontent.com/9960249/96977740-c5b2db00-151d-11eb-9847-586c1c4b1da6.png)

#### Expected Output
What you should get is
![image](https://user-images.githubusercontent.com/9960249/96977860-f1ce5c00-151d-11eb-8498-50280b8f18c8.png)

#### Output of ``psyplot -aV``

<details>

```
psy_maps.plugin:
  requirements:
    cartopy: 0.17.0
  version: 1.3.0+5.g0fc5e8c
psy_reg.plugin:
  requirements:
    scipy: 1.4.1
    statsmodels: 0.11.1
  version: 1.3.0+2.gd87aa82
psy_simple.plugin:
  version: 1.3.0+4.g9388e25
psy_strat.plugin:
  version: 0.1.0
psyplot:
  requirements:
    matplotlib: 3.2.1
    numpy: 1.18.4
    pandas: 1.0.3
    python: 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20)  [GCC
      7.3.0]
    xarray: 0.15.1
  version: 1.3.0+10.g867092b
psyplot_gui:
  requirements:
    pyqt: 5.12.3
    qt: 5.12.5
    qtconsole: 4.7.4
  version: 1.3.0+3.g7df7d45
psyplot_test.plugin:
  version: 1.0.0
```

</details>
