### ISSUE TITLE
mapvector: lonlatbox and density don't work together

### ISSUE THREAD

**Issue by victoria-cherkas** [psyplot/psy-maps#43]
#### Code Sample

```python
mapvectors = ds.psy.plot.mapvector(time=0,
                                lonlatbox=[0.,17.,42.,50.],
                                name=[['U', 'V']],
                                density=10, 
                                arrowsize=400, 
                                title='Vector Plot on Regular Grid')
```
#### Problem description

I dont seem to be able to get lonlatbox and density to work simultaneously on a vector plot. map_extent does work with density, but not lonlatbox.

#### Expected Output
Expect lonlatbox to work as usual when specifying arrow density in vectorplot.

#### Output of ``psyplot -aV``

<details>

```
psy_maps.plugin:
  requirements:
    cartopy: 0.20.2
  version: 1.4.1
psy_reg.plugin:
  requirements:
    scipy: 1.8.0
    statsmodels: 0.13.2
  version: 1.4.0
psy_simple.plugin:
  version: 1.4.1
psy_transect.plugin:
  version: 0.0.1.dev0
psyplot:
  requirements:
    matplotlib: 3.4.3
    numpy: 1.22.3
    pandas: 1.4.1
    python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46)  [GCC
      9.4.0]
    xarray: 2022.3.0
  version: 1.4.2
psyplot_gui:
  requirements:
    pyqt: 5.12.3
    qt: 5.12.9
    qtconsole: 5.3.0
  version: 1.4.0
```
</details>

#### NOTE
This is a bug report.
